app:
  baseUrl: https://backstage-apiplaybook-a22b57a14ff9.herokuapp.com

backend:
  baseUrl: https://backstage-apiplaybook-a22b57a14ff9.herokuapp.com
  listen:
    port: ${PORT}

catalog:
  locations: []
